AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Bootstrap Pipeline: Deploy service-level shared infrastructure (Cloud Map Service, LogGroup, ALB)'

Parameters:
  # =========================================================
  # Required Parameters
  # =========================================================
  PipelineName:
    Type: String
    Default: 'bootstrap-init'
    Description: 'Service Bootstrap Pipeline name'

  Env:
    Type: String
    Default: 'dev'
    AllowedValues: [ dev, test, preonline, online ]
    Description: 'Environment name'


  # =========================================================
  # Optional Parameters
  # =========================================================
  ConnectionArn:
    Type: String
    Default: 'arn:aws:codeconnections:us-east-1:297997107448:connection/9adfd918-2843-4147-9bc9-c4ee1a99bc39'
    Description: 'CodeStar connection ARN (GitHub integration)'

  ArtifactBucketName:
    Type: String
    Default: 'codepipeline-us-east-1-3622cd43956e-4d23-9284-a18746ff6c07'
    Description: 'S3 artifact bucket for CodePipeline artifacts'

  CloudFormationDeployRoleArn:
    Type: String
    Description: 'IAM Role ARN for CloudFormation deployments'

  CodePipelineRoleArn:
    Type: String
    Description: 'IAM Role ARN for CodePipeline'

  FullRepositoryId:
    Type: String
    Default: 'nianien/infra-devops'
    Description: 'GitHub repository ID (format: owner/repository)'

  RestartExecutionOnUpdate:
    Type: String
    Default: 'false'
    AllowedValues: [ 'true', 'false' ]
    Description: 'Whether to restart pipeline execution on update'

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${PipelineName}-${Env}'
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName

      Variables:
        - Name: Service
          DefaultValue: ''
          Description: 'ECS service name (e.g. demo-rpc or demo-api). Use lowercase letters, numbers, and hyphens only.'

      Stages:
        - Name: Source
          Actions:
            - Name: InfraSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: 'master'
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: InfraOut

        - Name: DeployServiceDiscovery
          Actions:
            - Name: CFNDeployServiceDiscovery
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub 'boot-sd-#{variables.Service}-${Env}'
                TemplatePath: 'InfraOut::ci/boot/templates/sd-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "ServiceName": "#{variables.Service}",
                    "Env": "${Env}",
                    "NamespaceStackName": "infra-namespace"
                  }

        - Name: DeployLog
          Actions:
            - Name: CFNDeployLog
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub 'boot-log-#{variables.Service}-${Env}'
                TemplatePath: 'InfraOut::ci/boot/templates/log-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "ServiceName": "#{variables.Service}",
                    "Env": "${Env}"
                  }

        - Name: DeployAlb
          Actions:
            - Name: CFNDeployAlb
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub 'boot-alb-#{variables.Service}-${Env}'
                TemplatePath: 'InfraOut::ci/boot/templates/alb-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "ServiceName": "#{variables.Service}",
                    "Env": "${Env}"
                  }

      RestartExecutionOnUpdate: !Ref RestartExecutionOnUpdate
      
      # 禁用所有阶段的自动转换，防止创建时自动触发
      DisableInboundStageTransitions:
        - StageName: DeployServiceDiscovery
          Reason: "Disable automatic transitions on pipeline creation"
        - StageName: DeployLog
          Reason: "Disable automatic transitions on pipeline creation"
        - StageName: DeployAlb
          Reason: "Disable automatic transitions on pipeline creation"

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
    Description: 'Service Bootstrap Pipeline Name'
