AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Bootstrap Pipeline: Deploy service-level shared infrastructure (Cloud Map Service, LogGroup, ALB)'

Parameters:
  # =========================================================
  # Required Parameters
  # =========================================================
  PipelineName:
    Type: String
    Default: 'bootstrap-init'
    Description: 'Service Bootstrap Pipeline name'

  Env:
    Type: String
    Default: 'dev'
    AllowedValues: [ dev, test, preonline, online ]
    Description: 'Environment name'


  # =========================================================
  # Optional Parameters
  # =========================================================
  ConnectionArn:
    Type: String
    Description: 'CodeStar connection ARN (GitHub integration)'

  CloudFormationDeployRoleArn:
    Type: String
    Description: 'IAM Role ARN for CloudFormation deployments'

  CodePipelineRoleArn:
    Type: String
    Description: 'IAM Role ARN for CodePipeline'

  FullRepositoryId:
    Type: String
    Default: 'nianien/infra-devops'
    Description: 'GitHub repository ID (format: owner/repository)'

  RestartExecutionOnUpdate:
    Type: String
    Default: 'false'
    AllowedValues: [ 'true', 'false' ]
    Description: 'Whether to restart pipeline execution on update'

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: ${pipeline_stack_name}_pipelineartifactbucket-xxxx
      VersioningConfiguration:
        Status: Enabled
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${PipelineName}-${Env}'
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket

      Variables:
        - Name: Service
          DefaultValue: 'demo-web-api'
          Description: 'ECS service name (e.g. demo-rpc or demo-api). Use lowercase letters, numbers, and hyphens only.'

      Stages:
        - Name: Source
          Actions:
            - Name: InfraSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: 'main'
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: InfraOut

        - Name: DeployBootstrap
          Actions:
            - Name: CFNDeployBootstrap
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub 'boot-#{variables.Service}-${Env}'
                TemplatePath: 'InfraOut::ci/boot/templates/boot-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "ServiceName": "#{variables.Service}",
                    "Env": "${Env}"
                  }

      RestartExecutionOnUpdate: !Ref RestartExecutionOnUpdate

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
    Description: 'Service Bootstrap Pipeline Name'
