AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure Pipeline: Deploy environment-level shared infrastructure (Network, Cloud Map Namespace)'

Parameters:
  # =========================================================
  # Required Parameters
  # =========================================================
  PipelineName:
    Type: String
    Description: 'Infrastructure Pipeline name (format: infra-<env>)'

  Env:
    Type: String
    Default: 'dev'
    AllowedValues: [ dev, test, preonline, online ]
    Description: 'Environment name'

  # =========================================================
  # Optional Parameters
  # =========================================================
  ConnectionArn:
    Type: String
    Default: 'arn:aws:codeconnections:us-east-1:297997107448:connection/9adfd918-2843-4147-9bc9-c4ee1a99bc39'
    Description: 'CodeStar connection ARN (GitHub integration)'

  ArtifactBucketName:
    Type: String
    Default: 'codepipeline-us-east-1-3622cd43956e-4d23-9284-a18746ff6c07'
    Description: 'S3 artifact bucket for CodePipeline artifacts'

  CloudFormationDeployRoleArn:
    Type: String
    Description: 'IAM Role ARN for CloudFormation deployments'

  CodePipelineRoleArn:
    Type: String
    Description: 'IAM Role ARN for CodePipeline'

  # =========================================================
  # Network Parameters
  # =========================================================
  # VPC 复用配置（留空则自建，非空则复用现有 VPC）
  VpcId:
    Type: String
    Default: ''
    Description: 'Existing VPC ID; leave empty to create a new VPC'

  PublicSubnets:
    Type: CommaDelimitedList
    Default: ''
    Description: 'Existing public subnet IDs when reusing (comma separated)'

  PrivateSubnets:
    Type: CommaDelimitedList
    Default: ''
    Description: 'Existing private subnet IDs when reusing (comma separated)'

  # VPC 创建配置（仅在 VpcId 为空时有效）
  VpcCidr:
    Type: String
    Default: '10.0.0.0/16'
    Description: 'VPC CIDR block (create mode only)'

  PublicSubnetCidr1:
    Type: String
    Default: '10.0.1.0/24'
    Description: 'Public subnet 1 CIDR block (create mode only)'

  PublicSubnetCidr2:
    Type: String
    Default: '10.0.2.0/24'
    Description: 'Public subnet 2 CIDR block (create mode only)'

  PrivateSubnetCidr1:
    Type: String
    Default: '10.0.11.0/24'
    Description: 'Private subnet 1 CIDR block (create mode only)'

  PrivateSubnetCidr2:
    Type: String
    Default: '10.0.12.0/24'
    Description: 'Private subnet 2 CIDR block (create mode only)'

  CreateNatGateways:
    Type: String
    AllowedValues: [ 'none', 'single', 'ha' ]
    Default: 'single'
    Description: "NAT strategy when creating VPC: 'none' | 'single' (cost-opt) | 'ha' (per-AZ)"

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName

      Stages:
        - Name: Source
          Actions:
            - Name: InfraSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: 'nianien/infra-devops'
                BranchName: 'master'
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: InfraOut

        - Name: DeployNetwork
          Actions:
            - Name: CFNDeployNetwork
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'infra-network'
                TemplatePath: 'InfraOut::ci/vpc-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "Env": "${Env}",
                    "VpcId": "${VpcId}",
                    "PublicSubnets": "${PublicSubnets}",
                    "PrivateSubnets": "${PrivateSubnets}",
                    "VpcCidr": "${VpcCidr}",
                    "PublicSubnetCidr1": "${PublicSubnetCidr1}",
                    "PublicSubnetCidr2": "${PublicSubnetCidr2}",
                    "PrivateSubnetCidr1": "${PrivateSubnetCidr1}",
                    "PrivateSubnetCidr2": "${PrivateSubnetCidr2}",
                    "CreateNatGateways": "${CreateNatGateways}"
                  }

        - Name: DeployNamespace
          Actions:
            - Name: CFNDeployNamespace
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'infra-namespace'
                TemplatePath: 'InfraOut::ci/namespace-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "Env": "${Env}"
                  }


      RestartExecutionOnUpdate: true

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
