version: 0.2

env:
  shell: bash
  variables:
    MODULE_PATH: "."                  # 相对"应用仓库根"（AppOut）
    DOCKERFILE_PATH: "ci/Dockerfile"  # 相对"应用仓库根"（AppOut）
    SKIP_TESTS: "1"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x ci/*.sh

  pre_build:
    commands:
      - . ci/prebuild.sh

  build:
    commands:
      - . ci/build.sh

  post_build:
    commands:
      - . ci/postbuild.sh

artifacts:
  files:
    - cfn-params.json   # 从主输入根目录打包