version: 0.2

env:
  shell: bash
  variables:
    MODULE_PATH: "."                  # 相对"应用仓库根"（AppOut）
    DOCKERFILE_PATH: "ci/Dockerfile"  # 相对"应用仓库根"（AppOut）
    SKIP_TESTS: "1"
  # 跨 phase 变量传递
  exported-variables:
    - ECR_REPO_URI
    - IMAGE_TAG_URI

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x ci/*.sh

  pre_build:
    commands:
      - '. ci/build.sh; prebuild'

  build:
    commands:
      - '. ci/build.sh; build'

  post_build:
    commands:
      - '. ci/build.sh; postbuild'

artifacts:
  files:
    - cfn-params.json   # 从主输入根目录打包