AWSTemplateFormatVersion: '2010-09-09'
Description: 'Log Stack: CloudWatch Log Group (shared infrastructure)'

Parameters:
  ServiceName:
    Type: String
    Description: 'Service name (e.g. user-service)'

  Env:
    Type: String
    Default: 'dev'
    Description: 'Environment name'

  LogRetentionDays:
    Type: Number
    Default: 30
    Description: 'Log retention period in days'


Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${Env}/${ServiceName}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub '/ecs/${Env}/${ServiceName}'
        - Key: Environment
          Value: !Ref Env
        - Key: Service
          Value: !Ref ServiceName

Outputs:
  LogGroupName:
    Description: 'CloudWatch Log Group Name'
    Value: !Sub '/ecs/${Env}/${ServiceName}'
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
