AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure Pipeline: Deploy environment-level shared infrastructure (Network, Cloud Map Namespace)'

Parameters:
  # =========================================================
  # Required Parameters
  # =========================================================
  PipelineName:
    Type: String
    Default: 'infra'
    Description: 'Infrastructure Pipeline name (format: infra-<env>)'

  Env:
    Type: String
    Default: 'dev'
    AllowedValues: [ dev, test, preonline, online ]
    Description: 'Environment name'

  # =========================================================
  # Optional Parameters
  # =========================================================
  ConnectionArn:
    Type: String
    Description: 'CodeStar connection ARN (GitHub integration)'


  CloudFormationDeployRoleArn:
    Type: String
    Description: 'IAM Role ARN for CloudFormation deployments'

  CodePipelineRoleArn:
    Type: String
    Description: 'IAM Role ARN for CodePipeline'

  # =========================================================
  # Network Parameters
  # =========================================================
  VpcCidr:
    Type: String
    Default: '10.0.0.0/16'
    Description: 'VPC CIDR block'

  PublicSubnetCidr1:
    Type: String
    Default: '10.0.1.0/24'
    Description: 'Public subnet 1 CIDR block'

  PublicSubnetCidr2:
    Type: String
    Default: '10.0.2.0/24'
    Description: 'Public subnet 2 CIDR block'

  PrivateSubnetCidr1:
    Type: String
    Default: '10.0.11.0/24'
    Description: 'Private subnet 1 CIDR block'

  PrivateSubnetCidr2:
    Type: String
    Default: '10.0.12.0/24'
    Description: 'Private subnet 2 CIDR block'

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: ${pipeline_stack_name}_pipelineartifactbucket-xxxx
      VersioningConfiguration:
        Status: Enabled
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${PipelineName}-${Env}'
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket

      Stages:
        - Name: Source
          Actions:
            - Name: InfraSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: 'nianien/infra-devops'
                BranchName: 'main'
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: InfraOut

        - Name: DeployNetwork
          Actions:
            - Name: CFNDeployNetwork
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'infra-network'
                TemplatePath: 'InfraOut::ci/infra/templates/vpc-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "Env": "${Env}",
                    "VpcCidr": "${VpcCidr}",
                    "PublicSubnetCidr1": "${PublicSubnetCidr1}",
                    "PublicSubnetCidr2": "${PublicSubnetCidr2}",
                    "PrivateSubnetCidr1": "${PrivateSubnetCidr1}",
                    "PrivateSubnetCidr2": "${PrivateSubnetCidr2}"
                  }

        - Name: DeployNamespace
          Actions:
            - Name: CFNDeployNamespace
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: InfraOut
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'infra-namespace'
                TemplatePath: 'InfraOut::ci/infra/templates/namespace-stack.yaml'
                RoleArn: !Ref CloudFormationDeployRoleArn
                Capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM'
                ParameterOverrides: !Sub |
                  {
                    "Env": "${Env}"
                  }
      RestartExecutionOnUpdate: true

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
